@HostAddress = http://localhost:5160

###
POST {{HostAddress}}/api/movies
Content-Type: application/json

{
    "title": "Inception",
    "genre": "Sci-Fi",
    "releaseYear": 2010,
    "isWatched": true,
    "rating": 10
}

###
GET {{HostAddress}}/api/movies

###
PUT {{HostAddress}}/api/movies/1
Content-Type: application/json

{
    "id": 1,
    "title": "Inception",
    "genre": "Sci-Fi",
    "releaseYear": 2010,
    "isWatched": true,
    "rating": 9
}

###
DELETE {{HostAddress}}/api/movies/1

###
PUT {{HostAddress}}/api/movies/7
Content-Type: application/json

{
    "id": 1,
    "firstName": "apitest",
    "lastName": "testapi",
    "email": "apiba",
    "isAatched": true
}

###
DELETE {{HostAddress}}/api/movies/6